backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: PreHeading, name: preHeading, widget: string}
          - {label: Heading, name: heading, widget: string}
          - {label: PostHeading, name: postHeading, widget: string}
          - {label: "Call to Action", name: main, widget: object, fields: [{label: preHeading, name: preHeading, widget: string}, {label: heading, name: heading, widget: text}, {label: actionText, name: actionText, widget: text}, {label: headingOptions, name: headingOptions, widget: list}]}
          - {label: Description, name: description, widget: string}
          - {label: Projects, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Image Alt, name: imageAlt, widget: text}, {label: "Background Image", name: backgroundImage, widget: image}, {label: Title, name: title, widget: text}, {label: linkURL, name: linkURL, widget: text}, {label: Skills, name: skills, widget: list}]}]}
      - file: "src/pages/header.md"
        label: "Header"
        name: "header"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "header-template"}
          - {label: title, name: title, widget: string}
          - {label: text, name: text, widget: string}
          - {label: textHighlight, name: textHighlight, widget: string}
          - {label: projectsHeading, name: projectsHeading, widget: string}
          - {label: contactHeading, name: contactHeading, widget: string}
          - {label: phone, name: phone, widget: string}
          - {label: email, name: email, widget: string}
          - {label: Projects, name: intro, widget: object, fields: [{label: Blurbs, name: blurbs, widget: list, fields: [{label: Text, name: text, widget: string}, {label: URL, name: url, widget: text}]}]}
      - file: "src/pages/footer.md"
        label: "Footer"
        name: "footer"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "footer-template"}
          - {label: email, name: email, widget: string}
          - {label: phone, name: phone, widget: string}
          - {label: copyright, name: copyright, widget: string}
